2017-09-09 11:05:56,630 [19920] ERROR SyncService-46104728 - UpdateWorld Exception：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 ConnectionComponent.GetForecast(Int32 frame) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Service\ServiceLogic\Component\ConnectionComponent.cs:行号 58
   在 ConnectionComponent.GetCommand(Int32 frame) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Service\ServiceLogic\Component\ConnectionComponent.cs:行号 28
   在 PlayerInputSystem`1.NoRecalcBeforeFixedUpdate(Int32 deltaTime) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Service\ServiceLogic\System\PlayerInputSystem.cs:行号 23
   在 WorldBase.NoRecalcBeforeFixedUpdate(Int32 deltaTime) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\ECS\WorldBase.cs:行号 284
   在 WorldBase.FixedLoop(Int32 deltaTime) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\ECS\WorldBase.cs:行号 231
   在 UpdateEngine.UpdateWorld(Int32 deltaTime) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Service\Game\UpdateEngine.cs:行号 66
2017-09-09 17:25:11,885 [31112] ERROR SyncService-46104728 - UpdateWorld Exception：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 ConnectionComponent.GetForecast(Int32 frame) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Service\ServiceLogic\Component\ConnectionComponent.cs:行号 61
   在 ConnectionComponent.GetCommand(Int32 frame) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Service\ServiceLogic\Component\ConnectionComponent.cs:行号 31
   在 PlayerInputSystem`1.NoRecalcBeforeFixedUpdate(Int32 deltaTime) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Service\ServiceLogic\System\PlayerInputSystem.cs:行号 23
   在 WorldBase.NoRecalcBeforeFixedUpdate(Int32 deltaTime) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\ECS\WorldBase.cs:行号 284
   在 WorldBase.FixedLoop(Int32 deltaTime) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\ECS\WorldBase.cs:行号 231
   在 UpdateEngine.UpdateWorld(Int32 deltaTime) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Service\Game\UpdateEngine.cs:行号 66
2017-09-09 18:17:38,644 [34644] ERROR SyncService-46104728 - methodIndex:301 Ex:System.Exception: AnalysisData Excepiton Data is ->commandcomponent<-
FieldName:->time<-
FieldType:->TYPE_int32<-
RepeatType:->RT_equired<-
CustomType:->syncvector3<-
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.get_Item(Int32 index)
   在 Protocol.ByteArray.ReadInt32() 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ByteArray.cs:行号 110
   在 Protocol.ProtocolReceiveFilter.ReadInt32(ByteArray ba) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 477
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 380
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 424
   在 Protocol.ProtocolReceiveFilter.Analysis(ByteArray bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 299
2017-09-09 18:17:38,644 [32804] ERROR SyncService-46104728 - methodIndex:301 Ex:System.Exception: AnalysisData Excepiton Data is ->commandcomponent<-
FieldName:->time<-
FieldType:->TYPE_int32<-
RepeatType:->RT_equired<-
CustomType:->syncvector3<-
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.get_Item(Int32 index)
   在 Protocol.ByteArray.ReadInt32() 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ByteArray.cs:行号 110
   在 Protocol.ProtocolReceiveFilter.ReadInt32(ByteArray ba) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 477
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 380
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 424
   在 Protocol.ProtocolReceiveFilter.Analysis(ByteArray bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 299
2017-09-09 18:18:26,938 [33212] ERROR SyncService-46104728 - methodIndex:301 Ex:System.Exception: AnalysisData Excepiton Data is ->commandcomponent<-
FieldName:->time<-
FieldType:->TYPE_int32<-
RepeatType:->RT_equired<-
CustomType:->syncvector3<-
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.get_Item(Int32 index)
   在 Protocol.ByteArray.ReadInt32() 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ByteArray.cs:行号 110
   在 Protocol.ProtocolReceiveFilter.ReadInt32(ByteArray ba) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 477
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 380
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 424
   在 Protocol.ProtocolReceiveFilter.Analysis(ByteArray bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 299
2017-09-09 18:20:32,258 [34584] ERROR SyncService-46104728 - methodIndex:301 Ex:System.Exception: AnalysisData Excepiton Data is ->commandcomponent<-
FieldName:->time<-
FieldType:->TYPE_int32<-
RepeatType:->RT_equired<-
CustomType:->syncvector3<-
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.get_Item(Int32 index)
   在 Protocol.ByteArray.ReadInt32() 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ByteArray.cs:行号 110
   在 Protocol.ProtocolReceiveFilter.ReadInt32(ByteArray ba) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 477
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 380
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 424
   在 Protocol.ProtocolReceiveFilter.Analysis(ByteArray bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 299
2017-09-09 18:20:32,258 [28400] ERROR SyncService-46104728 - methodIndex:301 Ex:System.Exception: AnalysisData Excepiton Data is ->commandcomponent<-
FieldName:->time<-
FieldType:->TYPE_int32<-
RepeatType:->RT_equired<-
CustomType:->syncvector3<-
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.get_Item(Int32 index)
   在 Protocol.ByteArray.ReadInt32() 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ByteArray.cs:行号 110
   在 Protocol.ProtocolReceiveFilter.ReadInt32(ByteArray ba) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 477
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 380
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 424
   在 Protocol.ProtocolReceiveFilter.Analysis(ByteArray bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 299
2017-09-09 18:24:10,629 [24644] ERROR SyncService-46104728 - methodIndex:301 Ex:System.Exception: AnalysisData Excepiton Data is ->commandcomponent<-
FieldName:->time<-
FieldType:->TYPE_int32<-
RepeatType:->RT_equired<-
CustomType:->syncvector3<-
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.get_Item(Int32 index)
   在 Protocol.ByteArray.ReadInt32() 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ByteArray.cs:行号 110
   在 Protocol.ProtocolReceiveFilter.ReadInt32(ByteArray ba) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 477
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 380
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 424
   在 Protocol.ProtocolReceiveFilter.Analysis(ByteArray bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 299
2017-09-09 18:24:10,632 [12700] ERROR SyncService-46104728 - methodIndex:301 Ex:System.Exception: AnalysisData Excepiton Data is ->commandcomponent<-
FieldName:->time<-
FieldType:->TYPE_int32<-
RepeatType:->RT_equired<-
CustomType:->syncvector3<-
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.get_Item(Int32 index)
   在 Protocol.ByteArray.ReadInt32() 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ByteArray.cs:行号 110
   在 Protocol.ProtocolReceiveFilter.ReadInt32(ByteArray ba) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 477
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 380
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 424
   在 Protocol.ProtocolReceiveFilter.Analysis(ByteArray bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 299
2017-09-09 18:25:45,521 [29692] ERROR SyncService-46104728 - methodIndex:301 Ex:System.Exception: AnalysisData Excepiton Data is ->commandcomponent<-
FieldName:->time<-
FieldType:->TYPE_int32<-
RepeatType:->RT_equired<-
CustomType:->syncvector3<-
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.get_Item(Int32 index)
   在 Protocol.ByteArray.ReadInt32() 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ByteArray.cs:行号 110
   在 Protocol.ProtocolReceiveFilter.ReadInt32(ByteArray ba) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 477
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 380
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 424
   在 Protocol.ProtocolReceiveFilter.Analysis(ByteArray bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 299
2017-09-09 18:25:45,526 [35628] ERROR SyncService-46104728 - methodIndex:301 Ex:System.Exception: AnalysisData Excepiton Data is ->commandcomponent<-
FieldName:->time<-
FieldType:->TYPE_int32<-
RepeatType:->RT_equired<-
CustomType:->syncvector3<-
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.get_Item(Int32 index)
   在 Protocol.ByteArray.ReadInt32() 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ByteArray.cs:行号 110
   在 Protocol.ProtocolReceiveFilter.ReadInt32(ByteArray ba) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 477
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 380
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 424
   在 Protocol.ProtocolReceiveFilter.Analysis(ByteArray bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 299
2017-09-09 18:27:35,782 [36004] ERROR SyncService-46104728 - methodIndex:301 Ex:System.Exception: AnalysisData Excepiton Data is ->commandcomponent<-
FieldName:->time<-
FieldType:->TYPE_int32<-
RepeatType:->RT_equired<-
CustomType:->syncvector3<-
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.get_Item(Int32 index)
   在 Protocol.ByteArray.ReadInt32() 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ByteArray.cs:行号 110
   在 Protocol.ProtocolReceiveFilter.ReadInt32(ByteArray ba) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 477
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 380
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 424
   在 Protocol.ProtocolReceiveFilter.Analysis(ByteArray bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 299
2017-09-09 18:27:35,811 [35996] ERROR SyncService-46104728 - methodIndex:301 Ex:System.Exception: AnalysisData Excepiton Data is ->commandcomponent<-
FieldName:->time<-
FieldType:->TYPE_int32<-
RepeatType:->RT_equired<-
CustomType:->syncvector3<-
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.get_Item(Int32 index)
   在 Protocol.ByteArray.ReadInt32() 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ByteArray.cs:行号 110
   在 Protocol.ProtocolReceiveFilter.ReadInt32(ByteArray ba) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 477
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 380
   在 Protocol.ProtocolReceiveFilter.AnalysisData(String MessageType, Byte[] bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 424
   在 Protocol.ProtocolReceiveFilter.Analysis(ByteArray bytes) 位置 F:\workTable\UnityProject\LockStepDemo\LockStepDemo\Server\LockStepDemo\Protocol\ProtocolReceiveFilter.cs:行号 299
